//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_LOG
    {
        public long ERROR_LOG_ID { get; set; }
        public Nullable<int> ERROR_NUMBER { get; set; }
        public Nullable<int> ERROR_LINE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string OBJECT_NAME { get; set; }
    }
}
