//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int id_pago { get; set; }
        public string Estado_pago { get; set; }
        public string Mes_pago { get; set; }
        public decimal Valor_extra { get; set; }
        public decimal Total_a_pagar { get; set; }
        public Nullable<int> Comprobante_id_com { get; set; }
        public Nullable<int> Plan_id_plan { get; set; }
        public Nullable<int> Contrato_id_cont { get; set; }
    
        public virtual Comprobantes Comprobantes { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
