//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int id_plan { get; set; }
        public string Tipo_plan { get; set; }
        public decimal Valor_plan { get; set; }
        public Nullable<int> Valor_ExtraChecklist { get; set; }
        public Nullable<int> Valor_ExtraAsesoria { get; set; }
        public Nullable<int> Valor_ExtraCapacitaciones { get; set; }
        public Nullable<int> Valor_ExtraInforme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
