//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesional()
        {
            this.Actividad = new HashSet<Actividad>();
            this.Cliente = new HashSet<Cliente>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id_prof { get; set; }
        public string Rut_prof { get; set; }
        public string Nombre_prof { get; set; }
        public string Apellido_prof { get; set; }
        public int Rendimiento_prof { get; set; }
        public string Estado_prof { get; set; }
        public System.DateTime Fecha_nacimiento_prof { get; set; }
        public string Mail_prof { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Nombre_completo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
